version: '3'
services:
  proxy:
    build: ./proxy
    container_name: proxy_container
    restart: always
    ports:
      - "80:80"
    networks:
      - wordpress-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mysql:8.0
    container_name: "db_container"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
       - wordpress-network

  wordpress:
    image: wordpress:6.0.3-php7.4-apache
    container_name: "wordpress_container"
    restart: always
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: onya-lab.site
      VIRTUAL_PORT: "80"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin
    container_name: "pma_container"
    restart: always
    environment:
      VIRTUAL_HOST: pma.onya-lab.site
      PMA_ARBITRARY: 1
      PMA_HOSTS: db
      PMA_USER: wp_user
      PMA_PASSWORD: Wordpress1!
    volumes:
      - ./phpmyadmin/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db: